version: '3.9'
name: 'home_hub'

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: always
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
    networks:
      mqtt_network:

  home_hub:
    container_name: home_hub
    build: ../
    depends_on:
      - mqtt
    restart: always
    volumes:
      - ../src/db/:/src/db/
    ports:
      - '9000:9000'
    networks:
      mqtt_network:

networks:
  mqtt_network:
