export const actionBusEvent = 'action'
export const deviceConDiscBusEvent = 'deviceConDisc'
export const onChangeDeviceStatusBusEvent = 'onChangeDeviceStatus'
export const changeDeviceStatusBusEvent = 'changeDeviceStatus'
export const sensorConDiscBusEvent = 'sensorConDisc'
